// Package config handles loading app-specific configuration and persona
// definitions. The tool is app-agnostic — all target app details live in
// config files.
package config

import (
	"fmt"
	"os"
	"path/filepath"
	"slices"
	"strings"

	"gopkg.in/yaml.v3"

	"github.com/VoterBloc/gollm-qa/internal/agent"
	"github.com/VoterBloc/gollm-qa/internal/provider"
)

// AppConfig defines a target application and the tools agents can use.
type AppConfig struct {
	Name    string       `yaml:"name"`
	BaseURL string       `yaml:"base_url"`
	Auth    AuthConfig   `yaml:"auth"`
	Tools   []ToolConfig `yaml:"tools"`
	Admin   AdminConfig  `yaml:"admin,omitempty"`
	// PersonaRegisterTemplate maps register_input field names to templates
	// that reference normalized identity fields generated by `gollm seed`.
	// Available placeholders: {{firstName}}, {{lastName}}, {{email}},
	// {{username}}, {{password}}. Used only by `gollm seed` to assemble
	// per-persona register_input blocks; runtime registration uses whatever
	// the persona YAML already contains.
	PersonaRegisterTemplate map[string]string `yaml:"persona_register_template,omitempty"`
	// ToolsFromSchema, when true, makes `gollm run` introspect the target
	// app's GraphQL schema and use the discovered queries/mutations as the
	// agent's tool set. Replaces (does not merge with) any hand-written
	// `tools:` block. Catches schema drift at config-load time rather than
	// on first call.
	ToolsFromSchema bool `yaml:"tools_from_schema,omitempty"`
	// ToolsInclude, when set, restricts auto-generated tools to the named
	// GraphQL operations (camelCase, as on Query/Mutation). Empty = include
	// everything. Only meaningful with ToolsFromSchema.
	ToolsInclude []string `yaml:"tools_include,omitempty"`
	// ToolsExclude removes named operations from the auto-generated set.
	// Applied after ToolsInclude. Only meaningful with ToolsFromSchema.
	ToolsExclude []string `yaml:"tools_exclude,omitempty"`
}

// AdminConfig describes admin-only operations (data purge, etc.). The admin
// path uses a pre-issued long-lived token rather than a login round-trip — a
// leaked .env should grant only what the token allows, not interactive admin
// access.
type AdminConfig struct {
	// TokenEnv is the env var name to read the admin auth token from. The
	// driver places the token directly into the auth header; no login call.
	TokenEnv string `yaml:"token_env"`
	// PurgeQuery is the GraphQL mutation that wipes synthetic data.
	PurgeQuery string `yaml:"purge_query"`
	// PurgeResultPath is a gjson path to the purge report inside the response.
	PurgeResultPath string `yaml:"purge_result_path"`
}

// AuthConfig defines how agents authenticate with the target app.
type AuthConfig struct {
	// Type is the auth mechanism — currently only "graphql" is supported.
	Type string `yaml:"type"`
	// Query is the GraphQL mutation (or REST endpoint) for login.
	Query string `yaml:"query"`
	// TokenPath is a gjson path to extract the token from the response.
	TokenPath string `yaml:"token_path"`
	// RegisterQuery is the GraphQL mutation used to create a new user (e.g.
	// registerForTest). Optional — only needed for run modes that seed users.
	RegisterQuery string `yaml:"register_query"`
	// RegisterTokenPath is a gjson path to extract the token from the register
	// response. If empty, register is treated as create-only and the caller is
	// expected to follow up with Login.
	RegisterTokenPath string `yaml:"register_token_path"`
	// HeaderName is the HTTP header for the auth token (default "Authorization").
	HeaderName string `yaml:"header_name"`
	// HeaderValue is the header value template. {{token}} is replaced with the actual token.
	HeaderValue string `yaml:"header_value"`
}

// ToolConfig maps an LLM-visible tool to a GraphQL operation.
type ToolConfig struct {
	Name        string        `yaml:"name"`
	Description string        `yaml:"description"`
	Query       string        `yaml:"query"`
	Parameters  []ParamConfig `yaml:"parameters"`
	ResultPath  string        `yaml:"result_path"`
	// Context is free-form text appended to the tool result before the LLM sees it.
	// Use it to provide affordance hints: what the agent can do next given what it just saw.
	Context string `yaml:"context"`
}

// ParamConfig defines a single parameter for a tool. Composes recursively:
// objects expand via Properties, arrays via Items, restricted-set strings
// via EnumValues. ToProviderTool walks this tree to build the JSON Schema
// the LLM sees in the tool spec.
type ParamConfig struct {
	Name        string `yaml:"name"`
	Type        string `yaml:"type"` // string, integer, number, boolean, object, array
	Description string `yaml:"description"`
	Required    bool   `yaml:"required"`
	// Properties is the nested ParamConfig list when Type == "object".
	// Each entry's Required flag contributes to the parent object's
	// `required` array in the generated JSON Schema.
	Properties []ParamConfig `yaml:"properties,omitempty"`
	// Items describes the element type when Type == "array". A pointer
	// rather than a value because a leaf-array's items have no name and
	// embedding feels misleading in YAML.
	Items *ParamConfig `yaml:"items,omitempty"`
	// EnumValues constrains a string to a fixed set (GraphQL enum).
	EnumValues []string `yaml:"enum,omitempty"`
}

// LoadAppConfig reads an app config YAML file and parses it.
func LoadAppConfig(path string) (*AppConfig, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("reading app config: %w", err)
	}
	return ParseAppConfig(data)
}

// ParseAppConfig parses raw YAML (or JSON, since JSON is valid YAML)
// bytes into an AppConfig. Applies defaults and runs validation. Used
// by LoadAppConfig and by the HTTP server's inline-config path so both
// loading routes share the same defaults / validation.
func ParseAppConfig(data []byte) (*AppConfig, error) {
	var cfg AppConfig
	if err := yaml.Unmarshal(data, &cfg); err != nil {
		return nil, fmt.Errorf("parsing app config: %w", err)
	}

	// Apply defaults.
	if cfg.Auth.HeaderName == "" {
		cfg.Auth.HeaderName = "Authorization"
	}
	if cfg.Auth.HeaderValue == "" {
		cfg.Auth.HeaderValue = "Bearer {{token}}"
	}

	if err := cfg.validate(); err != nil {
		return nil, err
	}

	return &cfg, nil
}

func (cfg *AppConfig) validate() error {
	if cfg.Name == "" {
		return fmt.Errorf("app config: name is required")
	}
	if cfg.BaseURL == "" {
		return fmt.Errorf("app config: base_url is required")
	}
	if cfg.Auth.Type != "" && cfg.Auth.Query == "" {
		return fmt.Errorf("app config: auth.query is required when auth.type is set")
	}
	if cfg.Auth.Type != "" && cfg.Auth.TokenPath == "" {
		return fmt.Errorf("app config: auth.token_path is required when auth.type is set")
	}
	for i, t := range cfg.Tools {
		if t.Name == "" {
			return fmt.Errorf("app config: tools[%d].name is required", i)
		}
		if t.Query == "" {
			return fmt.Errorf("app config: tools[%d].query is required", i)
		}
	}
	return nil
}

// LoadPersonas reads all YAML files from a directory and returns personas.
func LoadPersonas(dir string) ([]*agent.Persona, error) {
	entries, err := os.ReadDir(dir)
	if err != nil {
		return nil, fmt.Errorf("reading persona directory: %w", err)
	}

	// Sort for deterministic ordering across filesystems.
	slices.SortFunc(entries, func(a, b os.DirEntry) int {
		return strings.Compare(a.Name(), b.Name())
	})

	var personas []*agent.Persona
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		ext := strings.ToLower(filepath.Ext(entry.Name()))
		if ext != ".yaml" && ext != ".yml" {
			continue
		}

		path := filepath.Join(dir, entry.Name())
		data, err := os.ReadFile(path)
		if err != nil {
			return nil, fmt.Errorf("reading persona %s: %w", entry.Name(), err)
		}
		p, err := ParsePersona(data)
		if err != nil {
			return nil, fmt.Errorf("parsing persona %s: %w", entry.Name(), err)
		}
		personas = append(personas, p)
	}

	return personas, nil
}

// ParsePersona parses raw YAML (or JSON, since JSON is valid YAML)
// bytes into a Persona. Used by LoadPersonas and by the HTTP server's
// inline-personas path so both loading routes share the same shape.
func ParsePersona(data []byte) (*agent.Persona, error) {
	var p agent.Persona
	if err := yaml.Unmarshal(data, &p); err != nil {
		return nil, err
	}
	return &p, nil
}

// ToProviderTool converts a ToolConfig to the provider.Tool format the LLM
// sees. Walks ParamConfig trees recursively so nested objects (GraphQL
// INPUT_OBJECT) and arrays produce real JSON Schema shapes, not stringified
// hints — without this, the LLM sends `{"input": "{...}"}` (string) and
// GraphQL servers reject it as "Expected type 'Map' but was 'String'".
func (tc *ToolConfig) ToProviderTool() provider.Tool {
	return provider.Tool{
		Name:        tc.Name,
		Description: tc.Description,
		Parameters:  paramsToSchema(tc.Parameters),
	}
}

// paramsToSchema renders a ParamConfig slice as a JSON Schema object.
// Used both for the top-level tool parameters and recursively for nested
// object Properties.
func paramsToSchema(params []ParamConfig) map[string]any {
	properties := make(map[string]any, len(params))
	var required []string
	for _, p := range params {
		properties[p.Name] = paramToSchema(p)
		if p.Required {
			required = append(required, p.Name)
		}
	}
	schema := map[string]any{
		"type":       "object",
		"properties": properties,
	}
	if len(required) > 0 {
		schema["required"] = required
	}
	return schema
}

// paramToSchema renders a single ParamConfig as a JSON Schema fragment.
func paramToSchema(p ParamConfig) map[string]any {
	schema := map[string]any{
		"type": mapParamType(p.Type),
	}
	if p.Description != "" {
		schema["description"] = p.Description
	}
	if len(p.EnumValues) > 0 {
		schema["enum"] = p.EnumValues
	}
	switch strings.ToLower(p.Type) {
	case "object":
		nested := make(map[string]any, len(p.Properties))
		var nestedRequired []string
		for _, sub := range p.Properties {
			nested[sub.Name] = paramToSchema(sub)
			if sub.Required {
				nestedRequired = append(nestedRequired, sub.Name)
			}
		}
		schema["properties"] = nested
		if len(nestedRequired) > 0 {
			schema["required"] = nestedRequired
		}
	case "array":
		if p.Items != nil {
			schema["items"] = paramToSchema(*p.Items)
		}
	}
	return schema
}

func mapParamType(t string) string {
	switch strings.ToLower(t) {
	case "string":
		return "string"
	case "integer", "int":
		return "integer"
	case "boolean", "bool":
		return "boolean"
	case "number", "float":
		return "number"
	case "object":
		return "object"
	case "array":
		return "array"
	default:
		return "string"
	}
}
